@echo off
echo Running tests with coverage...
cd %~dp0
go test -coverprofile=coverage.out ./toolbox/...
echo Generating HTML coverage report...
go tool cover -html=coverage.out -o coverage.html
echo Coverage report generated as coverage.html
start coverage.html